[package]
edition = "2021"
exclude = ["index.node"]
license = "GPL-3.0"
name = "desktop_native"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[features]
default=[]
manual_test=[]

[dependencies]
anyhow = "1.0"
napi = {version = "2.9.1", features = ["async"]}
napi-derive = "2.9.1"
scopeguard = "1.1.0"
tokio = {version = "1.17.0", features = ["full"]}

[build-dependencies]
napi-build = "2.0.1"

[target.'cfg(windows)'.dependencies]
widestring = "0.5.1"
windows = {version = "0.39.0", features = [
  "Foundation",
  "Security_Credentials_UI",
  "Storage_Streams",
  "Win32_Foundation",
  "Win32_Security_Credentials",
  "Win32_System_WinRT",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
]}

[target.'cfg(windows)'.dev-dependencies]
keytar = "0.1.6"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.3"
security-framework = "2.6.1"
security-framework-sys = "2.6.1"

[target.'cfg(target_os = "linux")'.dependencies]
gio = "0.15.6"
libsecret = "0.1.4"
