---
name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    name: EnforceLabel
    runs-on: ubuntu-20.04
    steps:
      - name: Enforce Label
        uses: yogevbd/enforce-label-action@8d1e1709b1011e6d90400a0e6cf7c0b77aa5efeb  # v2.1.0
        with:
          BANNED_LABELS: "hold,needs-qa"
          BANNED_LABELS_DESCRIPTION: "PRs with the hold or needs-qa labels cannot be merged"
