---
name: Version Bump

on:
  workflow_dispatch:
    inputs:
      client:
        description: "Client Project"
        required: true
        type: choice
        options:
          - Browser
          - CLI
          - Desktop
          - Web
      version_number:
        description: "New Version"
        required: true

defaults:
  run:
    shell: bash

jobs:
  bump_version:
    name: "Bump ${{ github.event.inputs.client }} Version"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Login to Azure - Prod Subscription
        uses: Azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
        with:
         creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@c3b3285993151c5af47cefcb3b9134c28ab479af
        with:
          keyvault: "bitwarden-prod-kv"
          secrets: "github-gpg-private-key, github-gpg-private-key-passphrase"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@c8bb57c57e8df1be8c73ff3d59deab1dbc00e0d1
        with:
          gpg_private_key: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key }}
          passphrase: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key-passphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Version Branch
        id: branch
        env:
          CLIENT_NAME: ${{ github.event.inputs.client }}
          VERSION: ${{ github.event.inputs.version_number }}
        run: |
          CLIENT=$(python -c "print('$CLIENT_NAME'.lower())")
          echo "::set-output name=client::$CLIENT"

          git switch -c ${CLIENT}_version_bump_${VERSION}

      ########################
      # VERSION BUMP SECTION #
      ########################

      ### Browser
      - name: Bump Browser Version
        if: ${{ github.event.inputs.client == 'Browser' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version --workspace=@bitwarden/browser ${VERSION}

      - name: Bump Browser Version - Manifest
        if: ${{ github.event.inputs.client == 'Browser' }}
        uses: bitwarden/gh-actions/version-bump@03ad9a873c39cdc95dd8d77dbbda67f84db43945
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "apps/browser/src/manifest.json"

      - name: Bump Browser Version - Manifest v3
        if: ${{ github.event.inputs.client == 'Browser' }}
        uses: bitwarden/gh-actions/version-bump@03ad9a873c39cdc95dd8d77dbbda67f84db43945
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "apps/browser/src/manifest.v3.json"

      - name: Run Prettier after Browser Version Bump
        if: ${{ github.event.inputs.client == 'Browser' }}
        run: |
          npm install -g prettier
          prettier --write apps/browser/src/manifest.json
          prettier --write apps/browser/src/manifest.v3.json

      ### CLI
      - name: Bump CLI Version
        if: ${{ github.event.inputs.client == 'CLI' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version --workspace=@bitwarden/cli ${VERSION}

      ### Desktop
      - name: Bump Desktop Version - Root
        if: ${{ github.event.inputs.client == 'Desktop' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version --workspace=@bitwarden/desktop ${VERSION}

      - name: Bump Desktop Version - App
        if: ${{ github.event.inputs.client == 'Desktop' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version ${VERSION}
        working-directory: "apps/desktop/src"

      ### Web
      - name: Bump Web Version
        if: ${{ github.event.inputs.client == 'Web' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version --workspace=@bitwarden/web-vault ${VERSION}

      ########################

      - name: Setup git
        run: |
          git config --local user.email "106330231+bitwarden-devops-bot@users.noreply.github.com"
          git config --local user.name "bitwarden-devops-bot"

      - name: Check if version changed
        id: version-changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=changes_to_commit::TRUE"
          else
            echo "::set-output name=changes_to_commit::FALSE"
            echo "No changes to commit!";
          fi

      - name: Commit files
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          CLIENT: ${{ steps.branch.outputs.client }}
          VERSION: ${{ github.event.inputs.version_number }}
        run: |
          git commit -m "Bumped ${CLIENT} version to ${VERSION}" -a

      - name: Push changes
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          CLIENT: ${{ steps.branch.outputs.client }}
          VERSION: ${{ github.event.inputs.version_number }}
        run: git push -u origin ${CLIENT}_version_bump_${VERSION}

      - name: Create Bump Version PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          PR_BRANCH: "${{ steps.branch.outputs.client }}_version_bump_${{ github.event.inputs.version_number }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BASE_BRANCH: master
          TITLE: "Bump ${{ github.event.inputs.client }} version to ${{ github.event.inputs.version_number }}"
        run: |
          gh pr create --title "$TITLE" \
            --base "$BASE" \
            --head "$PR_BRANCH" \
            --label "version update" \
            --label "automated pr" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [X] Other

              ## Objective
              Automated ${{ github.event.inputs.client }} version bump to ${{ github.event.inputs.version_number }}"
